#!/bin/bash

cd /usr/share/textingapplication/client
BROWSER=none npm start 1> /dev/null &
npm run electron-prod-dev 1> /dev/null &

cd -

echo "Starting Server..."
/usr/share/textingapplication/server/WebServer
